### ISSUE TITLE
I want to change a special day to a start date, is there a way?

### ISSUE THREAD

**Issue by 92pino** [FaiChou/react-native-slideable-calendar-strip#12]
For example, what should I do if I want to start on 12/24?

**Comment by FaiChou** [comment]
There is no property on master branch to support this feature.
But I create a branch [initial_date_support](https://github.com/FaiChou/react-native-slideable-calendar-strip/tree/initial_date_support) for this.

## CAVEAT
This branch is lack of test and you can check my commit [here](https://github.com/FaiChou/react-native-slideable-calendar-strip/commit/01e5e5bfe86f8c5461cd2697af0be0695b1d796a) for better understand.

And use it with `goToday`, it may be weird because `today` is your initial date.

https://github.com/FaiChou/react-native-slideable-calendar-strip/blob/master/lib/CalendarStrip.js#L225
